### PR TITLE
Automatic search for implemented RPG functions added

### PR DESCRIPTION
**Pull request by szsascha**
See Issue #13

### CODE REVIEW

**Comment by worksofliam** [comment]
@SaschaS93 I really like this change.

I want to merge it - but can you implement this for all existing BIFs, operations and internal APIs? (the only existing system API is `printf`).

Let me know what your plans are.

Liam

**Comment by szsascha** [comment]
All tests were fine. RPGCode/system_printf.rpgle is working too. I've just check that.

The Annotation is just needed if the class name does not match the name of the RPG function. Please check the issue. I've explained it there with more details.

**Comment by worksofliam** [comment]
Yup I just finally had a real look at the code and the comments and really can't thank you enough for this great contribution!

I will merge when I get back from my errand this evening.

Thanks so much!

**Comment by szsascha** [comment]
Did some more work. Have added substring. Replace is in planning.

**Comment by worksofliam** [comment]
Thanks @SaschaS93 this has been merged!

**Pull request merged**
