### PR TITLE
Attempt at implementation of data queue APIs

### PR DESCRIPTION
**Pull request by worksofliam**
This is an attempt at implementing the data queue APIs as internal APIs.

It seems to be working correctly but would like it to be reviewed before merging.

### CODE REVIEW

**Review by szsascha — COMMENTED** [review]
Looks awesome!

Maybe I would use an Interface to implement "DataQueues". It makes it more easier to use different implementations, like MQ for example.

**Comment by worksofliam** [comment]
@SaschaS93 Good idea!

I will build the interface and then I'll get it merged.

Liam

**Comment by worksofliam** [comment]
@SaschaS93 Ok, I made the `IDataQueue` interface and am wondering if you can take another look to tell me what you think.

Specifically this does the work: https://github.com/worksofbarry/NetRPG/blob/42f7bd2be1eccbd0d2a4333c049bbe1a07d06f5a/NetRPG/Runtime/Functions/System/DataQueue.cs

**Comment by szsascha** [comment]
Hey, that's better! Now it's easier to extend.

**Pull request merged**
