### PR TITLE
Organizational changes for unit tests

### PR DESCRIPTION
**Pull request by szsascha**

### CODE REVIEW

**Comment by worksofliam** [comment]
@SaschaS93 If you're moving sources around, perhaps it might be also worth migrating stuff out of the `objects` folder too?

Thanks,
Liam

**Comment by szsascha** [comment]
Sorry I overlooked them.

Now I moved all files into the QSYS.LIB tree.

I tested it, but please look over it again.

**Comment by worksofliam** [comment]
@SaschaS93 I am curious as to why we are following the `.lib`, `.file`, etc standard?

Do we really need to do that? Let me know.

**Comment by worksofliam** [comment]
Also, after we decide to merge this PR then I will start working on some fixed-format support :)

**Comment by szsascha** [comment]
I'm really looking forward to the fixed format extensions!

Regarding the extensions I didn't really thought about the standard extensions. I just made it that way by habit. But it's a very good question.

For the file extensions we have to use i like names. (.rpgle, .dspf) So why not for the folders too?

I'd leave it that way for now. Only for historical reasons. ;)
But I don't really care. If you want to have it without .file and .lib, just tell me, then I will change it.

**Comment by worksofliam** [comment]
I am still not sure about this PR. 

I feel like with this we may have to think about implementing a runtime library list to find file definitions (and other bits). I won't merge for now but I will probably still make a start on the fixed-format implementation.

**Comment by worksofliam** [comment]
@SaschaS93 I will close this PR for now. I think now that we have the possibility to implement fixed format support we should do that.

**Comment by szsascha** [comment]
Ok. I just created a branch "changed-folder-structure" on my fork to save the changes. My master is now like your master again.

**Pull request closed without merging**
